networks:
  flytonica:
services:
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx_all.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - flytonica
  #   depends_on:
  #     - frontend
  frontend:
    build:
      context: ./
    networks:
      - flytonica
    ports:
      - 3000:3000
  # backend:
  #   build:
  #     context: ./flytonica_support_api
  #   networks:
  #     - flytonica

  
